### ISSUE TITLE
req.body.roles.forEach is not a function

### ISSUE THREAD

**Issue by Kanmuruuruu** [JuAlexandre/nodejs-mysql-auth#10]
` req.body.roles.forEach(role => {
        if (!roles.includes(role)) {
          throw { type: 'not_exist', role };
        }
      });`

**Comment by jualexandre** [comment]
The body of the request should be constructed as follows:

```json
{
	"email": "email@gmail.com",
	"username": "username",
	"password": "password",
	"roles": ["moderator"]
}
```

If you use Postman you must check the `raw` option for the body of the request.
